#!/usr/bin/env bash

spaces (){
	# Get the currently focused monitor
	FOCUSED_MONITOR=$(hyprctl monitors -j | jq -r '.[] | select(.focused == true) | .name')
	
	# Set the workspace range based on the focused monitor
	if [ "$FOCUSED_MONITOR" = "HDMI-A-1" ]; then
		WORKSPACE_RANGE="11 20"
	else
		WORKSPACE_RANGE="1 10"
	fi

	WORKSPACE_WINDOWS=$(hyprctl workspaces -j | jq 'map({key: .id | tostring, value: .windows}) | from_entries')
	seq $WORKSPACE_RANGE | jq --argjson windows "${WORKSPACE_WINDOWS}" --slurp -Mc 'map(tostring) | map({id: ., windows: ($windows[.]//0)})'
}

spaces
socat -u UNIX-CONNECT:$XDG_RUNTIME_DIR/hypr/$HYPRLAND_INSTANCE_SIGNATURE/.socket2.sock - | while read -r line; do
	spaces
done