#!/bin/bash

# Load environment variables from .env file
SCRIPT_DIR="$(dirname "$0")"
source "$SCRIPT_DIR/.env"

# Calculate dates
TO_DATE=$(date -u +"%Y-%m-%dT%H:%M:%SZ")
WEEKS_TO_FETCH=17  # Approximately 4 months
FROM_DATE=$(date -u -d "$(date -d "-$WEEKS_TO_FETCH weeks" "+%Y-%m-%d") -$(date -d "-$WEEKS_TO_FETCH weeks" +%u) days" +"%Y-%m-%dT%H:%M:%SZ")

# Construct GraphQL query
read -r -d '' QUERY <<EOF
query {
  user(login: "$GITHUB_USERNAME") {
    contributionsCollection(from: "$FROM_DATE", to: "$TO_DATE") {
      contributionCalendar {
        totalContributions
        weeks {
          firstDay
          contributionDays {
            date
            contributionCount
            color
          }
        }
      }
    }
  }
}
EOF

# Echo the raw GraphQL query for debugging
#echo "GraphQL query:"
#echo "$QUERY"

# Construct JSON payload using jq to ensure proper escaping
JSON_PAYLOAD=$(jq -n --arg query "$QUERY" '{query: $query}')

# Echo the JSON payload for debugging
#echo "JSON payload:"
#echo "$JSON_PAYLOAD"


# Make the API request
curl -s -H "Content-Type: application/json" \
     -H "Authorization: bearer $GITHUB_TOKEN" \
     -X POST \
     -d "$JSON_PAYLOAD" \
     https://api.github.com/graphql
